Repository The-Arcadis-Team/arc-station-14, pull requests merged in 2024-09, with the labels that each got.

#47 Eris goes insane, 2025
  Content.Server/Objectives/Components/StoreUnlockerComponent.cs
  Content.Server/Objectives/Systems/StoreUnlockerSystem.cs
  Content.Server/Store/Conditions/ObjectiveUnlockCondition.cs
  Content.Shared/Cabinet/ItemCabinetSystem.cs
  Content.Shared/Cabinet/SealingCabinetComponent.cs
  Content.Shared/Cabinet/SealingCabinetSystem.cs
  Resources/Locale/en-US/nuke/nuke-core-container.ftl
  Resources/Locale/en-US/objectives/conditions/steal.ftl
  Resources/Locale/en-US/store/categories.ftl
  Resources/Locale/en-US/store/uplink-catalog.ftl
  Resources/Locale/en-US/tools/tool-qualities.ftl
  Resources/Prototypes/Catalog/Fills/Items/toolboxes.yml
  Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
  Resources/Prototypes/Entities/Objects/Devices/Circuitboards/computer.yml
  Resources/Prototypes/Entities/Objects/Misc/plutonium_core.yml
  Resources/Prototypes/Entities/Objects/Tools/syndicate.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Machines/nuke.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Objectives/stealTargetGroups.yml
  Resources/Prototypes/Objectives/thief.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/nuke.yml
  Resources/Prototypes/Store/categories.yml
  Resources/Prototypes/Store/presets.yml
  Resources/Prototypes/tags.yml
  Resources/Prototypes/tool_qualities.yml
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/closed.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/core_closed.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/core_open.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/inhand-left.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/inhand-right.png
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/meta.json
  Resources/Textures/Objects/Misc/nuke_core_container.rsi/open.png
  Resources/Textures/Objects/Misc/plutonium_core.rsi/icon.png
  Resources/Textures/Objects/Misc/plutonium_core.rsi/meta.json
  Resources/migration.yml
Labels: Changes: Sprites

#56 Adding new hud glasses and fixing rsi shit
  Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
  Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
  Resources/Textures/Clothing/Eyes/Glasses/crglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/Clothing/Eyes/Glasses/crglasses.rsi/equipped-EYES.png
  Resources/Textures/Clothing/Eyes/Glasses/crglasses.rsi/icon.png
  Resources/Textures/Clothing/Eyes/Glasses/crglasses.rsi/inhand-left.png
  Resources/Textures/Clothing/Eyes/Glasses/crglasses.rsi/inhand-right.png
  Resources/Textures/Clothing/Eyes/Glasses/crglasses.rsi/meta.json
  Resources/Textures/Clothing/Eyes/Glasses/medglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/Clothing/Eyes/Glasses/medglasses.rsi/equipped-EYES.png
  Resources/Textures/Clothing/Eyes/Glasses/medglasses.rsi/icon.png
  Resources/Textures/Clothing/Eyes/Glasses/medglasses.rsi/inhand-left.png
  Resources/Textures/Clothing/Eyes/Glasses/medglasses.rsi/inhand-right.png
  Resources/Textures/Clothing/Eyes/Glasses/medglasses.rsi/meta.json
  Resources/Textures/Clothing/Eyes/Glasses/medsecglasses.rsi/equipped-EYES-hamster.png
  Resources/Textures/Clothing/Eyes/Glasses/medsecglasses.rsi/equipped-EYES.png
  Resources/Textures/Clothing/Eyes/Glasses/medsecglasses.rsi/icon.png
  Resources/Textures/Clothing/Eyes/Glasses/medsecglasses.rsi/inhand-left.png
  Resources/Textures/Clothing/Eyes/Glasses/medsecglasses.rsi/inhand-right.png
  Resources/Textures/Clothing/Eyes/Glasses/medsecglasses.rsi/meta.json
Labels: Changes: Sprites, No C#, Status: Needs Review

#68 Added both fbi cap and fbi coat.
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/icon.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/inhand-left.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/inhand-right.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/inhand-left.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/inhand-right.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/meta.json
Labels: Changes: Sprites, No C#, Status: Awaiting Changes

#73 Revert "Added both fbi cap and fbi coat."
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/icon.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/inhand-left.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/inhand-right.png
  Resources/Textures/Clothing/Head/Hats/fbicap.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/inhand-left.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/inhand-right.png
  Resources/Textures/Clothing/OuterClothing/Coats/fbisuit.rsi/meta.json
Labels: Changes: Sprites, No C#

#74 fix custom vendor adverts
  Resources/Locale/en-US/advertisements/vending/erpdrobe.ftl
  Resources/Locale/en-US/advertisements/vending/merc.ftl
  Resources/Locale/en-US/advertisements/vending/ntpd.ftl
Labels: No C#

#75 Admeme Invisiwalls.
  Resources/Locale/en-US/advertisements/vending/erpdrobe.ftl
  Resources/Locale/en-US/advertisements/vending/merc.ftl
  Resources/Prototypes/Entities/Markers/Spawners/Spawners - Shortcut.lnk
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
Labels: No C#, Status: Needs Review
